# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://lukemshepherd.github.io/London_COVID_maps/"

git_url = "https://github.com/lukemshepherd/London_COVID_maps/tree/master/"

def custom_doc_links(name): return None
